### ISSUE TITLE
[PE-D][Tester D] delete /recur error

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-3/tp#130] opened 2024-11-08 13:49 UTC
```
> list /recur
1. CATEGORY: food   DESCRIPTION: chicken rice   PRICE: 4.50   DATE ADDED: 08-11-2024   LAST ADDED DATE: 08-11-2024   FREQUENCY: daily
2. CATEGORY: abcd112312   DESCRIPTION: chicken rice   PRICE: 4.50   DATE ADDED: 08-11-2024   LAST ADDED DATE: 08-11-2024   FREQUENCY: daily
> delete /recur 1
Invalid Arguments.
> delete /recur 2
Invalid Arguments.
> delete /recur 0
Invalid Arguments.
```

Cannot perform delete /recur INDEX

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tkhahns/ped#3

**Comment by Hackin7** [comment] 2024-11-08 21:35
A duplicate of https://github.com/AY2425S1-CS2113-W12-3/tp/issues/138

**Closed by Hackin7** 2024-11-08 21:35 UTC
Labels: type.Documentation
